# Testcase Structure:
#    name: String, // The name of the testcase
#    subname: Option<String>, // used for unittests later
#    testcase_type: String, //Only IO supported now
#    description: Option<String>, // optional description
#    args: Option<String>, // command line arguments
#    cflags: Option<String>, // compile flags
#    tags: Option<Tags>, // tags for unit tests
#    in_file: Option<String>, // stdin file
#    exp_file: Option<String>, // stdout file
#    in_string: Option<String>, // stdin string (in_file has higher priority)
#    exp_string: Option<String>, // stdout string (out_file has higher priority)
#    exp_retvar: Option<i32>, // optional expected status code
#    timeout: Option<i32>, // timeout in seconds .. default is 5 sec
#    env_vars: Option<String>, // optional environment parameters RAND_SEED=123,foo=bar
#    add_diff_mode: Option<String>, // diff-mode for additional file, can be "text" or "binary"
#    add_out_file: Option<String>, // additional student file to diff,
#    add_exp_file: Option<String>, // additional reference file to diff
#    protected: Option<bool>, // optional boolean, set to true to mark a testcase as private, false by default

[project_definition]
project_name = "oop1"
makefile_path = "."
maketarget = "all"


# public M1
[[testcases]]
name = 'valid_start_2_players'
testcase_type = "IO"
description = "2 players and EOF"
env_vars = 'RAND_SEED=174813'
exp_file = "tests/d1/01/out"
in_file = "tests/d1/01/in"
exp_retvar = 0
protected = false

[[testcases]]
name = 'invalid_players_number'
testcase_type = "IO"
description = "Negative and too big input for number of players, at the end 3 players"
env_vars = 'RAND_SEED=4483129'
exp_file = "tests/d1/02/out"
in_file = "tests/d1/02/in"
exp_retvar = 0
protected = false

[[testcases]]
name = 'cli_parameters'
testcase_type = "IO"
description = "Some cli parameters"
env_vars = 'RAND_SEED=4483129'
args = ['oop1', 'is', 'cool']
exp_file = "tests/d1/03/out"
exp_retvar = 2
protected = false


# public M2
[[testcases]]
name = 'show/hidetreasure'
testcase_type = "IO"
description = "All possible version of show- and hidetreasure commands"
env_vars = 'RAND_SEED=1543129'
exp_file = "tests/d2/01/out"
in_file = "tests/d2/01/in"
exp_retvar = 0
protected = false

[[testcases]]
name = 'directions'
testcase_type = "IO"
description = "Standard version of directional commands"
env_vars = 'RAND_SEED=1543129'
exp_file = "tests/d2/02/out"
in_file = "tests/d2/02/in"
exp_retvar = 0
protected = false

[[testcases]]
name = 'directions_Advanced'
testcase_type = "IO"
description = "Directional commands with several fields"
env_vars = 'RAND_SEED=1543129'
exp_file = "tests/d2/03/out"
in_file = "tests/d2/03/in"
exp_retvar = 0
protected = false

[[testcases]]
name = 'showfreetile'
testcase_type = "IO"
description = "All possible version of showfreetile command"
env_vars = 'RAND_SEED=1543129'
exp_file = "tests/d2/04/out"
in_file = "tests/d2/04/in"
exp_retvar = 0
protected = false

[[testcases]]
name = 'rotate'
testcase_type = "IO"
description = "All possible version of rotate command"
env_vars = 'RAND_SEED=1543129'
exp_file = "tests/d2/05/out"
in_file = "tests/d2/05/in"
exp_retvar = 0
protected = false

[[testcases]]
name = 'insert_valid'
testcase_type = "IO"
description = "All possible valid version of insert command"
env_vars = 'RAND_SEED=1543129'
exp_file = "tests/d2/06/out"
in_file = "tests/d2/06/in"
exp_retvar = 0
protected = false

[[testcases]]
name = 'gamefield'
testcase_type = "IO"
description = "All version of gamefield command"
env_vars = 'RAND_SEED=1543129'
exp_file = "tests/d2/07/out"
in_file = "tests/d2/07/in"
exp_retvar = 0
protected = false

[[testcases]]
name = 'go_direction_not_allowed'
testcase_type = "IO"
description = "Player wants to walk through a wall"
env_vars = 'RAND_SEED=1543129'
exp_file = "tests/d2/08/out"
in_file = "tests/d2/08/in"
exp_retvar = 0
protected = false

[[testcases]]
name = 'playthrough_valid'
testcase_type = "IO"
description = "Full valid playthrough"
timeout = 20
env_vars = 'RAND_SEED=1543129'
exp_file = "tests/d2/09/out"
in_file = "tests/d2/09/in"
exp_retvar = 0
protected = false
